# Generated by Django 4.2.21 on 2025-06-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='publication_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
