# Generated by Django 4.2.21 on 2025-06-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_publicitycost_cost_alter_sale_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
